name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NODE_VERSION: '22'

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run type-check

      - name: Run linting
        run: npm run lint:strict

      - name: Run format check
        run: npm run format:check

      - name: Run tests
        run: npm run test:ci
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs: quality-checks
    if: github.event_name == 'pull_request'
    environment:
      name: Preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview to Vercel
        id: deploy
        run: |
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          echo "Preview deployed to: $DEPLOYMENT_URL"

      - name: Comment PR with Preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.deploy.outputs.url }}';
            const comment = `🚀 **Preview Deployment Ready!**\n\n🔗 [View Preview](${url})\n\n✅ All quality checks passed`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: [canary-deployment]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: Production
      url: https://scentmatch.vercel.app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Post-deployment Health Check
        run: |
          sleep 30  # Allow production deployment to fully initialize
          curl -f https://scentmatch.vercel.app/api/health || exit 1
          curl -f https://scentmatch.vercel.app/ || exit 1
          echo "✅ Production health check passed"

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://scentmatch.vercel.app
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Notify deployment success
        uses: actions/github-script@v7
        with:
          script: |
            const deploymentInfo = {
              environment: 'Production',
              url: 'https://scentmatch.vercel.app',
              commit: context.sha.slice(0, 7),
              branch: context.ref.replace('refs/heads/', ''),
              timestamp: new Date().toISOString(),
            };

            console.log('🚀 Production deployment successful!');
            console.log('📊 Deployment info:', deploymentInfo);

  performance-check:
    name: Performance Validation
    runs-on: ubuntu-latest
    needs: deploy-production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Web Vitals Check
        run: |
          npm install -g @unlighthouse/cli
          unlighthouse-ci --site https://scentmatch.vercel.app --build-static

      - name: Upload Performance Report
        uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: .unlighthouse/

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run enhanced security audit
        run: |
          npm audit --audit-level=moderate
          npx audit-ci --moderate

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Security headers validation
        run: |
          echo "Validating security headers configuration..."
          grep -q "X-Frame-Options" middleware.ts || exit 1
          grep -q "Content-Security-Policy" middleware.ts || exit 1
          grep -q "Strict-Transport-Security" middleware.ts || exit 1

  canary-deployment:
    name: Canary Deployment
    runs-on: ubuntu-latest
    needs: [quality-checks, security-scan]
    if: github.ref == 'refs/heads/main'
    environment:
      name: Canary
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Canary
        id: deploy
        run: |
          CANARY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$CANARY_URL" >> $GITHUB_OUTPUT
          echo "Canary deployed to: $CANARY_URL"

      - name: Run Smoke Tests on Canary
        run: |
          sleep 30  # Allow deployment to fully initialize
          curl -f ${{ steps.deploy.outputs.url }}/api/health || exit 1
          curl -f ${{ steps.deploy.outputs.url }}/ || exit 1
          echo "✅ Canary smoke tests passed"

      - name: Performance Test Canary
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: ${{ steps.deploy.outputs.url }}
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Core Web Vitals Validation
        run: |
          echo "Validating Core Web Vitals on canary deployment..."
          # Additional performance validation can be added here
          echo "✅ Performance validation completed"

  deployment-failure-notification:
    name: Deployment Failure Notification
    runs-on: ubuntu-latest
    needs: [canary-deployment, deploy-production]
    if: failure() && github.ref == 'refs/heads/main'

    steps:
      - name: Notify deployment failure
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Production Deployment Failed',
              body: `
              # Production Deployment Failure Alert
              
              **Workflow**: [${context.workflow}](${context.payload.repository.html_url}/actions/runs/${context.runId})
              **Branch**: ${context.ref.replace('refs/heads/', '')}
              **Commit**: ${context.sha.slice(0, 7)}
              **Timestamp**: ${new Date().toISOString()}
              
              ## Failed Jobs
              - Canary Deployment: ${{ needs.canary-deployment.result }}
              - Production Deployment: ${{ needs.deploy-production.result }}
              
              ## Immediate Actions Required
              1. Check workflow logs for specific failure details
              2. Verify Vercel deployment status
              3. Test critical user journeys manually
              4. Consider rollback if production is affected
              
              ## Rollback Command
              \`\`\`bash
              # If production deployment failed, rollback previous version
              vercel rollback https://scentmatch.vercel.app --token=\$VERCEL_TOKEN
              \`\`\`
              
              ## Health Check
              - [ ] API Health: https://scentmatch.vercel.app/api/health
              - [ ] Homepage: https://scentmatch.vercel.app/
              - [ ] Quiz Flow: https://scentmatch.vercel.app/quiz
              `,
              labels: ['bug', 'deployment', 'urgent', 'production']
            });

            console.log(\`Created deployment failure issue: \${issue.data.html_url}\`);
